# Generated by Django 4.2 on 2023-04-11 02:10

import api.models.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('last_heartbeat', models.DateTimeField()),
            ],
            bases=(models.Model, api.models.base.BaseModel),
        ),
        migrations.CreateModel(
            name='SensorCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('acked', models.BooleanField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensor')),
            ],
            bases=(models.Model, api.models.base.BaseModel),
        ),
    ]
