# Generated by Django 4.2 on 2023-04-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_userprofile_ledprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledprofile',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
