# Generated by Django 4.2 on 2023-04-10 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_payment_userprofile_delete_ledprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
