# Generated by Django 4.2 on 2023-04-10 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveIntegerField(default=0)),
                ('green', models.PositiveIntegerField(default=0)),
                ('blue', models.PositiveIntegerField(default=0)),
                ('otp_secret', models.CharField(blank=True, max_length=64, null=True)),
                ('opt_out_led', models.BooleanField(default=False)),
                ('opt_out_social', models.BooleanField(default=False)),
                ('opt_out_hacker_points', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mehmberprofile.userprofile')),
            ],
        ),
    ]
