# Generated by Django 4.2 on 2023-04-10 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mehmberprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='led_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200)],
                                      verbose_name='LED Number'),
        ),
    ]
