# Generated by Django 4.2 on 2023-04-10 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mehmberprofile', '0003_payment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_out_ledwall', models.BooleanField(default=False)),
                ('opt_out_socialbot', models.BooleanField(default=False)),
                ('opt_out_accoladestracking', models.BooleanField(default=False)),
                ('opt_out_doorapptracking', models.BooleanField(default=False)),
                ('hackerspace_rgb', models.CharField(max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('member_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mehmberprofile.memberprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='MehmberProfile',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
