# Generated by Django 4.2 on 2023-04-10 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mehmberprofile', '0003_membershiphistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiphistory',
            name='date',
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
