# Generated by Django 4.2 on 2023-04-10 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehmberprofile', '0004_memberprofile_paymenthistory_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
