# Generated by Django 4.2 on 2023-04-10 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mehmberprofile', '0004_remove_membershiphistory_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiphistory',
            name='amount',
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=11,
                                      validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='led_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200),
                                                                         django.core.validators.MinValueValidator(0)],
                                      verbose_name='LED Number'),
        ),
    ]
