# Generated by Django 4.2 on 2023-04-10 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehmberprofile', '0005_alter_paymenthistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='hackerspace_rgb',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='rgb_blue',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='rgb_green',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='rgb_red',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
