# Generated by Django 4.2 on 2023-04-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehmberprofile', '0007_rename_opt_out_accoladestracking_memberprofile_opt_out_accolades_tracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='opt_out_all_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
