# Generated by Django 4.2 on 2023-04-10 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehmberprofile', '0007_rename_membershiphistory_mehmbershiphistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='led_number',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)], verbose_name='LED Number'),
        ),
    ]
