# Generated by Django 4.2 on 2023-04-10 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehmberprofile', '0008_memberprofile_opt_out_all_tracking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberprofile',
            old_name='opt_out_accolades_tracking',
            new_name='opt_out_accoladestracking',
        ),
        migrations.RenameField(
            model_name='memberprofile',
            old_name='opt_out_doorapp_tracking',
            new_name='opt_out_doorapptracking',
        ),
        migrations.RenameField(
            model_name='memberprofile',
            old_name='opt_out_led_wall',
            new_name='opt_out_ledwall',
        ),
        migrations.RenameField(
            model_name='memberprofile',
            old_name='opt_out_social_bot',
            new_name='opt_out_socialbot',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='opt_out_all_tracking',
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='rgb_blue',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='rgb_green',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='rgb_red',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
    ]
