# Generated by Django 4.2 on 2023-04-10 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mehmberprofile', '0009_rename_opt_out_accolades_tracking_memberprofile_opt_out_accoladestracking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_out_all', models.BooleanField(default=False)),
                ('opt_out_led_wall', models.BooleanField(default=False)),
                ('opt_out_door_display', models.BooleanField(default=False)),
                ('opt_out_social_bot', models.BooleanField(default=False)),
                ('opt_out_accolade_display', models.BooleanField(default=False)),
                ('rgb_value', models.CharField(default='#000000', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='member_profile',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='description',
            field=models.CharField(default='Mehmbership', max_length=255),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='MemberProfile',
        ),
    ]
