name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: meh-api
          POSTGRES_PASSWORD: password
          POSTGRES_USER: meh-user
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry

        poetry install
    - name: Run Tests
      run: |
        make test
      env:
        DATABASE_URL: postgres://meh-user:password@localhost/meh-api
